### ISSUE TITLE
Problem with npm@5.0.3

### ISSUE THREAD

**Issue by MarekSalat** [tad-lispy/npm-git-install#23]
Hi, I have updated npm to 5.0.3 and npm-git-install does not work, my git dependency is not installed. There is simlink in node_modules, but it refers to an unavailable location :(

**Comment by MarekSalat** [comment]
but it seems like we do not need npm install anymore. I have to try this, but according to npm@5 changelog

Git dependencies support semver through user/repo#semver:^1.2.3 (#15308) (#15666) (@sankethkatta)

Git dependencies with prepare scripts will have their devDependencies installed, and npm install run in their directory before being packed.

**Comment by tad-lispy** [comment]
Hi, Marek!

As far as I understand with NPM 5 you should no longer need npm-git-install. See https://github.com/npm/npm/issues/3055#issuecomment-304698029 . This package is a workaround for the linked issue, and according to NPM team it is fixed in version 5.

I have not try it yet myself, but basically it should be enough if you move your dependencies from `gitDependencies` section to standard `dependencies` (or `devDependencies`). Provided the dependencies have correctly set `prepare` script it should just work.

Please share your experience. I'm really interested :)

**Comment by MarekSalat** [comment]
Good news! It works :)
add script to your package `"prepare": "npm run build",`
remove npm-git-install, remove gitDeps and add normal dep     `"<package-name>": "https://github.com/<repo>#<commitish-ref>",`

**Comment by tad-lispy** [comment]
Awesome! Closing in favour of #24 .
